package credCobGerClasses;

// Generated 06-24-2014 07:46:37 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Ahorro generated by hbm2java
 */
@Entity
@Table(name = "ahorro", catalog = "CredCobGer")
public class Ahorro implements java.io.Serializable {

	private AhorroId id;
	private BigDecimal salAho;
	private Date fecUltMovAho;
	private Date fecApeAho;

	public Ahorro() {
	}

	public Ahorro(AhorroId id, BigDecimal salAho, Date fecUltMovAho,
			Date fecApeAho) {
		this.id = id;
		this.salAho = salAho;
		this.fecUltMovAho = fecUltMovAho;
		this.fecApeAho = fecApeAho;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "codAho", column = @Column(name = "COD_AHO", nullable = false, length = 11)),
			@AttributeOverride(name = "codigoAs", column = @Column(name = "CODIGO_AS", nullable = false, length = 7)) })
	public AhorroId getId() {
		return this.id;
	}

	public void setId(AhorroId id) {
		this.id = id;
	}

	@Column(name = "SAL_AHO", nullable = false, precision = 10)
	public BigDecimal getSalAho() {
		return this.salAho;
	}

	public void setSalAho(BigDecimal salAho) {
		this.salAho = salAho;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FEC_ULT_MOV_AHO", nullable = false, length = 10)
	public Date getFecUltMovAho() {
		return this.fecUltMovAho;
	}

	public void setFecUltMovAho(Date fecUltMovAho) {
		this.fecUltMovAho = fecUltMovAho;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FEC_APE_AHO", nullable = false, length = 10)
	public Date getFecApeAho() {
		return this.fecApeAho;
	}

	public void setFecApeAho(Date fecApeAho) {
		this.fecApeAho = fecApeAho;
	}

}
