package credCobGerClasses;

// Generated 06-24-2014 07:46:37 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AhorroId generated by hbm2java
 */
@Embeddable
public class AhorroId implements java.io.Serializable {

	private String codAho;
	private String codigoAs;

	public AhorroId() {
	}

	public AhorroId(String codAho, String codigoAs) {
		this.codAho = codAho;
		this.codigoAs = codigoAs;
	}

	@Column(name = "COD_AHO", nullable = false, length = 11)
	public String getCodAho() {
		return this.codAho;
	}

	public void setCodAho(String codAho) {
		this.codAho = codAho;
	}

	@Column(name = "CODIGO_AS", nullable = false, length = 7)
	public String getCodigoAs() {
		return this.codigoAs;
	}

	public void setCodigoAs(String codigoAs) {
		this.codigoAs = codigoAs;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AhorroId))
			return false;
		AhorroId castOther = (AhorroId) other;

		return ((this.getCodAho() == castOther.getCodAho()) || (this
				.getCodAho() != null && castOther.getCodAho() != null && this
				.getCodAho().equals(castOther.getCodAho())))
				&& ((this.getCodigoAs() == castOther.getCodigoAs()) || (this
						.getCodigoAs() != null
						&& castOther.getCodigoAs() != null && this
						.getCodigoAs().equals(castOther.getCodigoAs())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getCodAho() == null ? 0 : this.getCodAho().hashCode());
		result = 37 * result
				+ (getCodigoAs() == null ? 0 : this.getCodigoAs().hashCode());
		return result;
	}

}
