package credCobGerClasses;

// Generated 06-24-2014 07:46:37 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Aportacion generated by hbm2java
 */
@Entity
@Table(name = "aportacion", catalog = "CredCobGer")
public class Aportacion implements java.io.Serializable {

	private AportacionId id;
	private BigDecimal saldoApo;
	private Date fecApeApo;
	private Date ultPagApo;

	public Aportacion() {
	}

	public Aportacion(AportacionId id, BigDecimal saldoApo, Date fecApeApo,
			Date ultPagApo) {
		this.id = id;
		this.saldoApo = saldoApo;
		this.fecApeApo = fecApeApo;
		this.ultPagApo = ultPagApo;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "codigoApo", column = @Column(name = "CODIGO_APO", nullable = false, length = 11)),
			@AttributeOverride(name = "codigoAs", column = @Column(name = "CODIGO_AS", nullable = false, length = 7)) })
	public AportacionId getId() {
		return this.id;
	}

	public void setId(AportacionId id) {
		this.id = id;
	}

	@Column(name = "SALDO_APO", nullable = false, precision = 10)
	public BigDecimal getSaldoApo() {
		return this.saldoApo;
	}

	public void setSaldoApo(BigDecimal saldoApo) {
		this.saldoApo = saldoApo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FEC_APE_APO", nullable = false, length = 10)
	public Date getFecApeApo() {
		return this.fecApeApo;
	}

	public void setFecApeApo(Date fecApeApo) {
		this.fecApeApo = fecApeApo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ULT_PAG_APO", nullable = false, length = 10)
	public Date getUltPagApo() {
		return this.ultPagApo;
	}

	public void setUltPagApo(Date ultPagApo) {
		this.ultPagApo = ultPagApo;
	}

}
