package credCobGerClasses;

// Generated 06-24-2014 07:46:37 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AportacionId generated by hbm2java
 */
@Embeddable
public class AportacionId implements java.io.Serializable {

	private String codigoApo;
	private String codigoAs;

	public AportacionId() {
	}

	public AportacionId(String codigoApo, String codigoAs) {
		this.codigoApo = codigoApo;
		this.codigoAs = codigoAs;
	}

	@Column(name = "CODIGO_APO", nullable = false, length = 11)
	public String getCodigoApo() {
		return this.codigoApo;
	}

	public void setCodigoApo(String codigoApo) {
		this.codigoApo = codigoApo;
	}

	@Column(name = "CODIGO_AS", nullable = false, length = 7)
	public String getCodigoAs() {
		return this.codigoAs;
	}

	public void setCodigoAs(String codigoAs) {
		this.codigoAs = codigoAs;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AportacionId))
			return false;
		AportacionId castOther = (AportacionId) other;

		return ((this.getCodigoApo() == castOther.getCodigoApo()) || (this
				.getCodigoApo() != null && castOther.getCodigoApo() != null && this
				.getCodigoApo().equals(castOther.getCodigoApo())))
				&& ((this.getCodigoAs() == castOther.getCodigoAs()) || (this
						.getCodigoAs() != null
						&& castOther.getCodigoAs() != null && this
						.getCodigoAs().equals(castOther.getCodigoAs())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getCodigoApo() == null ? 0 : this.getCodigoApo().hashCode());
		result = 37 * result
				+ (getCodigoAs() == null ? 0 : this.getCodigoAs().hashCode());
		return result;
	}

}
