package credCobGerClasses;

// Generated 06-24-2014 07:46:37 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Asociado generated by hbm2java
 */
@Entity
@Table(name = "asociado", catalog = "CredCobGer")
public class Asociado implements java.io.Serializable {

	private String codigoAs;
	private String nombreAs;
	private String apellidoAs;
	private String duiAs;
	private String nitAs;
	private String emailAs;
	private Date fechaNacAs;
	private Date fechaIngAs;
	private char directivoAs;
	private char empleadoAs;
	private Date actualizadoAs;
	private Integer edadMoraProm;
	private BigDecimal aportVsDeuda;
	private BigDecimal pagoPreFin;
	private BigDecimal razEndeu;

	public Asociado() {
	}

	public Asociado(String codigoAs, String nombreAs, String apellidoAs,
			String duiAs, String nitAs, Date fechaNacAs, Date fechaIngAs,
			char directivoAs, char empleadoAs, Date actualizadoAs) {
		this.codigoAs = codigoAs;
		this.nombreAs = nombreAs;
		this.apellidoAs = apellidoAs;
		this.duiAs = duiAs;
		this.nitAs = nitAs;
		this.fechaNacAs = fechaNacAs;
		this.fechaIngAs = fechaIngAs;
		this.directivoAs = directivoAs;
		this.empleadoAs = empleadoAs;
		this.actualizadoAs = actualizadoAs;
	}

	public Asociado(String codigoAs, String nombreAs, String apellidoAs,
			String duiAs, String nitAs, String emailAs, Date fechaNacAs,
			Date fechaIngAs, char directivoAs, char empleadoAs,
			Date actualizadoAs, Integer edadMoraProm, BigDecimal aportVsDeuda,
			BigDecimal pagoPreFin, BigDecimal razEndeu) {
		this.codigoAs = codigoAs;
		this.nombreAs = nombreAs;
		this.apellidoAs = apellidoAs;
		this.duiAs = duiAs;
		this.nitAs = nitAs;
		this.emailAs = emailAs;
		this.fechaNacAs = fechaNacAs;
		this.fechaIngAs = fechaIngAs;
		this.directivoAs = directivoAs;
		this.empleadoAs = empleadoAs;
		this.actualizadoAs = actualizadoAs;
		this.edadMoraProm = edadMoraProm;
		this.aportVsDeuda = aportVsDeuda;
		this.pagoPreFin = pagoPreFin;
		this.razEndeu = razEndeu;
	}

	@Id
	@Column(name = "CODIGO_AS", unique = true, nullable = false, length = 7)
	public String getCodigoAs() {
		return this.codigoAs;
	}

	public void setCodigoAs(String codigoAs) {
		this.codigoAs = codigoAs;
	}

	@Column(name = "NOMBRE_AS", nullable = false, length = 30)
	public String getNombreAs() {
		return this.nombreAs;
	}

	public void setNombreAs(String nombreAs) {
		this.nombreAs = nombreAs;
	}

	@Column(name = "APELLIDO_AS", nullable = false, length = 30)
	public String getApellidoAs() {
		return this.apellidoAs;
	}

	public void setApellidoAs(String apellidoAs) {
		this.apellidoAs = apellidoAs;
	}

	@Column(name = "DUI_AS", nullable = false, length = 10)
	public String getDuiAs() {
		return this.duiAs;
	}

	public void setDuiAs(String duiAs) {
		this.duiAs = duiAs;
	}

	@Column(name = "NIT_AS", nullable = false, length = 17)
	public String getNitAs() {
		return this.nitAs;
	}

	public void setNitAs(String nitAs) {
		this.nitAs = nitAs;
	}

	@Column(name = "EMAIL_AS", length = 40)
	public String getEmailAs() {
		return this.emailAs;
	}

	public void setEmailAs(String emailAs) {
		this.emailAs = emailAs;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FECHA_NAC_AS", nullable = false, length = 10)
	public Date getFechaNacAs() {
		return this.fechaNacAs;
	}

	public void setFechaNacAs(Date fechaNacAs) {
		this.fechaNacAs = fechaNacAs;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FECHA_ING_AS", nullable = false, length = 10)
	public Date getFechaIngAs() {
		return this.fechaIngAs;
	}

	public void setFechaIngAs(Date fechaIngAs) {
		this.fechaIngAs = fechaIngAs;
	}

	@Column(name = "DIRECTIVO_AS", nullable = false, length = 1)
	public char getDirectivoAs() {
		return this.directivoAs;
	}

	public void setDirectivoAs(char directivoAs) {
		this.directivoAs = directivoAs;
	}

	@Column(name = "EMPLEADO_AS", nullable = false, length = 1)
	public char getEmpleadoAs() {
		return this.empleadoAs;
	}

	public void setEmpleadoAs(char empleadoAs) {
		this.empleadoAs = empleadoAs;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ACTUALIZADO_AS", nullable = false, length = 10)
	public Date getActualizadoAs() {
		return this.actualizadoAs;
	}

	public void setActualizadoAs(Date actualizadoAs) {
		this.actualizadoAs = actualizadoAs;
	}

	@Column(name = "EDAD_MORA_PROM")
	public Integer getEdadMoraProm() {
		return this.edadMoraProm;
	}

	public void setEdadMoraProm(Integer edadMoraProm) {
		this.edadMoraProm = edadMoraProm;
	}

	@Column(name = "APORT_VS_DEUDA", precision = 10)
	public BigDecimal getAportVsDeuda() {
		return this.aportVsDeuda;
	}

	public void setAportVsDeuda(BigDecimal aportVsDeuda) {
		this.aportVsDeuda = aportVsDeuda;
	}

	@Column(name = "PAGO_PRE_FIN", precision = 10)
	public BigDecimal getPagoPreFin() {
		return this.pagoPreFin;
	}

	public void setPagoPreFin(BigDecimal pagoPreFin) {
		this.pagoPreFin = pagoPreFin;
	}

	@Column(name = "RAZ_ENDEU", precision = 10)
	public BigDecimal getRazEndeu() {
		return this.razEndeu;
	}

	public void setRazEndeu(BigDecimal razEndeu) {
		this.razEndeu = razEndeu;
	}

}
