package credCobGerClasses;

// Generated 06-24-2014 07:46:37 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Credito generated by hbm2java
 */
@Entity
@Table(name = "credito", catalog = "CredCobGer")
public class Credito implements java.io.Serializable {

	private CreditoId id;
	private int numLinCred;
	private String sucCre;
	private String nivAutCre;
	private String claActCre;
	private BigDecimal monBruCre;
	private BigDecimal otoNetCre;
	private BigDecimal aboCre;
	private Date ultFecPagCre;
	private BigDecimal pagIntCre;
	private BigDecimal pagSegCre;
	private BigDecimal pagManCre;
	private BigDecimal pagOtrosCre;
	private Date fecActCre;

	public Credito() {
	}

	public Credito(CreditoId id, int numLinCred, String claActCre,
			BigDecimal monBruCre, BigDecimal otoNetCre, BigDecimal aboCre,
			Date ultFecPagCre, BigDecimal pagIntCre, BigDecimal pagSegCre,
			BigDecimal pagManCre, BigDecimal pagOtrosCre, Date fecActCre) {
		this.id = id;
		this.numLinCred = numLinCred;
		this.claActCre = claActCre;
		this.monBruCre = monBruCre;
		this.otoNetCre = otoNetCre;
		this.aboCre = aboCre;
		this.ultFecPagCre = ultFecPagCre;
		this.pagIntCre = pagIntCre;
		this.pagSegCre = pagSegCre;
		this.pagManCre = pagManCre;
		this.pagOtrosCre = pagOtrosCre;
		this.fecActCre = fecActCre;
	}

	public Credito(CreditoId id, int numLinCred, String sucCre,
			String nivAutCre, String claActCre, BigDecimal monBruCre,
			BigDecimal otoNetCre, BigDecimal aboCre, Date ultFecPagCre,
			BigDecimal pagIntCre, BigDecimal pagSegCre, BigDecimal pagManCre,
			BigDecimal pagOtrosCre, Date fecActCre) {
		this.id = id;
		this.numLinCred = numLinCred;
		this.sucCre = sucCre;
		this.nivAutCre = nivAutCre;
		this.claActCre = claActCre;
		this.monBruCre = monBruCre;
		this.otoNetCre = otoNetCre;
		this.aboCre = aboCre;
		this.ultFecPagCre = ultFecPagCre;
		this.pagIntCre = pagIntCre;
		this.pagSegCre = pagSegCre;
		this.pagManCre = pagManCre;
		this.pagOtrosCre = pagOtrosCre;
		this.fecActCre = fecActCre;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "codCre", column = @Column(name = "COD_CRE", nullable = false, length = 11)),
			@AttributeOverride(name = "codigoAs", column = @Column(name = "CODIGO_AS", nullable = false, length = 7)) })
	public CreditoId getId() {
		return this.id;
	}

	public void setId(CreditoId id) {
		this.id = id;
	}

	@Column(name = "NUM_LIN_CRED", nullable = false)
	public int getNumLinCred() {
		return this.numLinCred;
	}

	public void setNumLinCred(int numLinCred) {
		this.numLinCred = numLinCred;
	}

	@Column(name = "SUC_CRE", length = 10)
	public String getSucCre() {
		return this.sucCre;
	}

	public void setSucCre(String sucCre) {
		this.sucCre = sucCre;
	}

	@Column(name = "NIV_AUT_CRE", length = 10)
	public String getNivAutCre() {
		return this.nivAutCre;
	}

	public void setNivAutCre(String nivAutCre) {
		this.nivAutCre = nivAutCre;
	}

	@Column(name = "CLA_ACT_CRE", nullable = false, length = 2)
	public String getClaActCre() {
		return this.claActCre;
	}

	public void setClaActCre(String claActCre) {
		this.claActCre = claActCre;
	}

	@Column(name = "MON_BRU_CRE", nullable = false, precision = 10)
	public BigDecimal getMonBruCre() {
		return this.monBruCre;
	}

	public void setMonBruCre(BigDecimal monBruCre) {
		this.monBruCre = monBruCre;
	}

	@Column(name = "OTO_NET_CRE", nullable = false, precision = 10)
	public BigDecimal getOtoNetCre() {
		return this.otoNetCre;
	}

	public void setOtoNetCre(BigDecimal otoNetCre) {
		this.otoNetCre = otoNetCre;
	}

	@Column(name = "ABO_CRE", nullable = false, precision = 10)
	public BigDecimal getAboCre() {
		return this.aboCre;
	}

	public void setAboCre(BigDecimal aboCre) {
		this.aboCre = aboCre;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ULT_FEC_PAG_CRE", nullable = false, length = 10)
	public Date getUltFecPagCre() {
		return this.ultFecPagCre;
	}

	public void setUltFecPagCre(Date ultFecPagCre) {
		this.ultFecPagCre = ultFecPagCre;
	}

	@Column(name = "PAG_INT_CRE", nullable = false, precision = 10)
	public BigDecimal getPagIntCre() {
		return this.pagIntCre;
	}

	public void setPagIntCre(BigDecimal pagIntCre) {
		this.pagIntCre = pagIntCre;
	}

	@Column(name = "PAG_SEG_CRE", nullable = false, precision = 10)
	public BigDecimal getPagSegCre() {
		return this.pagSegCre;
	}

	public void setPagSegCre(BigDecimal pagSegCre) {
		this.pagSegCre = pagSegCre;
	}

	@Column(name = "PAG_MAN_CRE", nullable = false, precision = 10)
	public BigDecimal getPagManCre() {
		return this.pagManCre;
	}

	public void setPagManCre(BigDecimal pagManCre) {
		this.pagManCre = pagManCre;
	}

	@Column(name = "PAG_OTROS_CRE", nullable = false, precision = 10)
	public BigDecimal getPagOtrosCre() {
		return this.pagOtrosCre;
	}

	public void setPagOtrosCre(BigDecimal pagOtrosCre) {
		this.pagOtrosCre = pagOtrosCre;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FEC_ACT_CRE", nullable = false, length = 10)
	public Date getFecActCre() {
		return this.fecActCre;
	}

	public void setFecActCre(Date fecActCre) {
		this.fecActCre = fecActCre;
	}

}
