package credCobGerClasses;

// Generated 06-24-2014 07:46:37 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DepositoPlazoId generated by hbm2java
 */
@Embeddable
public class DepositoPlazoId implements java.io.Serializable {

	private String codigoDep;
	private String codigoAs;

	public DepositoPlazoId() {
	}

	public DepositoPlazoId(String codigoDep, String codigoAs) {
		this.codigoDep = codigoDep;
		this.codigoAs = codigoAs;
	}

	@Column(name = "CODIGO_DEP", nullable = false, length = 11)
	public String getCodigoDep() {
		return this.codigoDep;
	}

	public void setCodigoDep(String codigoDep) {
		this.codigoDep = codigoDep;
	}

	@Column(name = "CODIGO_AS", nullable = false, length = 7)
	public String getCodigoAs() {
		return this.codigoAs;
	}

	public void setCodigoAs(String codigoAs) {
		this.codigoAs = codigoAs;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DepositoPlazoId))
			return false;
		DepositoPlazoId castOther = (DepositoPlazoId) other;

		return ((this.getCodigoDep() == castOther.getCodigoDep()) || (this
				.getCodigoDep() != null && castOther.getCodigoDep() != null && this
				.getCodigoDep().equals(castOther.getCodigoDep())))
				&& ((this.getCodigoAs() == castOther.getCodigoAs()) || (this
						.getCodigoAs() != null
						&& castOther.getCodigoAs() != null && this
						.getCodigoAs().equals(castOther.getCodigoAs())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getCodigoDep() == null ? 0 : this.getCodigoDep().hashCode());
		result = 37 * result
				+ (getCodigoAs() == null ? 0 : this.getCodigoAs().hashCode());
		return result;
	}

}
