package credCobGerClasses;

// Generated 06-24-2014 07:46:37 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DepositoPlazo generated by hbm2java
 */
@Entity
@Table(name = "deposito_plazo", catalog = "CredCobGer")
public class DepositoPlazo implements java.io.Serializable {

	private DepositoPlazoId id;
	private BigDecimal montoDep;
	private BigDecimal saldoDep;
	private Date apertDep;
	private Date vencDep;
	private Date ultPagoDep;

	public DepositoPlazo() {
	}

	public DepositoPlazo(DepositoPlazoId id, BigDecimal montoDep,
			BigDecimal saldoDep, Date apertDep, Date vencDep, Date ultPagoDep) {
		this.id = id;
		this.montoDep = montoDep;
		this.saldoDep = saldoDep;
		this.apertDep = apertDep;
		this.vencDep = vencDep;
		this.ultPagoDep = ultPagoDep;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "codigoDep", column = @Column(name = "CODIGO_DEP", nullable = false, length = 11)),
			@AttributeOverride(name = "codigoAs", column = @Column(name = "CODIGO_AS", nullable = false, length = 7)) })
	public DepositoPlazoId getId() {
		return this.id;
	}

	public void setId(DepositoPlazoId id) {
		this.id = id;
	}

	@Column(name = "MONTO_DEP", nullable = false, precision = 10)
	public BigDecimal getMontoDep() {
		return this.montoDep;
	}

	public void setMontoDep(BigDecimal montoDep) {
		this.montoDep = montoDep;
	}

	@Column(name = "SALDO_DEP", nullable = false, precision = 10)
	public BigDecimal getSaldoDep() {
		return this.saldoDep;
	}

	public void setSaldoDep(BigDecimal saldoDep) {
		this.saldoDep = saldoDep;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "APERT_DEP", nullable = false, length = 10)
	public Date getApertDep() {
		return this.apertDep;
	}

	public void setApertDep(Date apertDep) {
		this.apertDep = apertDep;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "VENC_DEP", nullable = false, length = 10)
	public Date getVencDep() {
		return this.vencDep;
	}

	public void setVencDep(Date vencDep) {
		this.vencDep = vencDep;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ULT_PAGO_DEP", nullable = false, length = 10)
	public Date getUltPagoDep() {
		return this.ultPagoDep;
	}

	public void setUltPagoDep(Date ultPagoDep) {
		this.ultPagoDep = ultPagoDep;
	}

}
