package credCobGerClasses;

// Generated 06-24-2014 07:46:37 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * LineaCredito generated by hbm2java
 */
@Entity
@Table(name = "linea_credito", catalog = "CredCobGer")
public class LineaCredito implements java.io.Serializable {

	private int numLinCred;
	private String nomLinCred;

	public LineaCredito() {
	}

	public LineaCredito(int numLinCred, String nomLinCred) {
		this.numLinCred = numLinCred;
		this.nomLinCred = nomLinCred;
	}

	@Id
	@Column(name = "NUM_LIN_CRED", unique = true, nullable = false)
	public int getNumLinCred() {
		return this.numLinCred;
	}

	public void setNumLinCred(int numLinCred) {
		this.numLinCred = numLinCred;
	}

	@Column(name = "NOM_LIN_CRED", nullable = false, length = 20)
	public String getNomLinCred() {
		return this.nomLinCred;
	}

	public void setNomLinCred(String nomLinCred) {
		this.nomLinCred = nomLinCred;
	}

}
