package credCobGerClasses;

// Generated 06-24-2014 07:46:37 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * OtorgaId generated by hbm2java
 */
@Embeddable
public class OtorgaId implements java.io.Serializable {

	private int numLinCred;
	private int numCorrSuc;

	public OtorgaId() {
	}

	public OtorgaId(int numLinCred, int numCorrSuc) {
		this.numLinCred = numLinCred;
		this.numCorrSuc = numCorrSuc;
	}

	@Column(name = "NUM_LIN_CRED", nullable = false)
	public int getNumLinCred() {
		return this.numLinCred;
	}

	public void setNumLinCred(int numLinCred) {
		this.numLinCred = numLinCred;
	}

	@Column(name = "NUM_CORR_SUC", nullable = false)
	public int getNumCorrSuc() {
		return this.numCorrSuc;
	}

	public void setNumCorrSuc(int numCorrSuc) {
		this.numCorrSuc = numCorrSuc;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof OtorgaId))
			return false;
		OtorgaId castOther = (OtorgaId) other;

		return (this.getNumLinCred() == castOther.getNumLinCred())
				&& (this.getNumCorrSuc() == castOther.getNumCorrSuc());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getNumLinCred();
		result = 37 * result + this.getNumCorrSuc();
		return result;
	}

}
