package credCobGerClasses;

// Generated 06-24-2014 07:46:37 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ProyMensId generated by hbm2java
 */
@Embeddable
public class ProyMensId implements java.io.Serializable {

	private int mesPm;
	private String codigoRubro;

	public ProyMensId() {
	}

	public ProyMensId(int mesPm, String codigoRubro) {
		this.mesPm = mesPm;
		this.codigoRubro = codigoRubro;
	}

	@Column(name = "MES_PM", nullable = false)
	public int getMesPm() {
		return this.mesPm;
	}

	public void setMesPm(int mesPm) {
		this.mesPm = mesPm;
	}

	@Column(name = "CODIGO_RUBRO", nullable = false, length = 2)
	public String getCodigoRubro() {
		return this.codigoRubro;
	}

	public void setCodigoRubro(String codigoRubro) {
		this.codigoRubro = codigoRubro;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ProyMensId))
			return false;
		ProyMensId castOther = (ProyMensId) other;

		return (this.getMesPm() == castOther.getMesPm())
				&& ((this.getCodigoRubro() == castOther.getCodigoRubro()) || (this
						.getCodigoRubro() != null
						&& castOther.getCodigoRubro() != null && this
						.getCodigoRubro().equals(castOther.getCodigoRubro())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getMesPm();
		result = 37
				* result
				+ (getCodigoRubro() == null ? 0 : this.getCodigoRubro()
						.hashCode());
		return result;
	}

}
