package credCobGerClasses;

// Generated 06-24-2014 07:46:37 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ProyMens generated by hbm2java
 */
@Entity
@Table(name = "proy_mens", catalog = "CredCobGer")
public class ProyMens implements java.io.Serializable {

	private ProyMensId id;
	private int anhoPm;
	private BigDecimal realizadoPm;
	private BigDecimal metaPm;

	public ProyMens() {
	}

	public ProyMens(ProyMensId id, int anhoPm, BigDecimal realizadoPm,
			BigDecimal metaPm) {
		this.id = id;
		this.anhoPm = anhoPm;
		this.realizadoPm = realizadoPm;
		this.metaPm = metaPm;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "mesPm", column = @Column(name = "MES_PM", nullable = false)),
			@AttributeOverride(name = "codigoRubro", column = @Column(name = "CODIGO_RUBRO", nullable = false, length = 2)) })
	public ProyMensId getId() {
		return this.id;
	}

	public void setId(ProyMensId id) {
		this.id = id;
	}

	@Column(name = "ANHO_PM", nullable = false)
	public int getAnhoPm() {
		return this.anhoPm;
	}

	public void setAnhoPm(int anhoPm) {
		this.anhoPm = anhoPm;
	}

	@Column(name = "REALIZADO_PM", nullable = false, precision = 10)
	public BigDecimal getRealizadoPm() {
		return this.realizadoPm;
	}

	public void setRealizadoPm(BigDecimal realizadoPm) {
		this.realizadoPm = realizadoPm;
	}

	@Column(name = "META_PM", nullable = false, precision = 10)
	public BigDecimal getMetaPm() {
		return this.metaPm;
	}

	public void setMetaPm(BigDecimal metaPm) {
		this.metaPm = metaPm;
	}

}
