package credCobGerClasses;

// Generated 06-24-2014 07:46:37 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ProyAnual generated by hbm2java
 */
@Entity
@Table(name = "proy_anual", catalog = "CredCobGer")
public class ProyAnual implements java.io.Serializable {

	private ProyAnualId id;
	private BigDecimal realizado;
	private BigDecimal meta;

	public ProyAnual() {
	}

	public ProyAnual(ProyAnualId id, BigDecimal realizado, BigDecimal meta) {
		this.id = id;
		this.realizado = realizado;
		this.meta = meta;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "anho", column = @Column(name = "ANHO", nullable = false)),
			@AttributeOverride(name = "codigoRubro", column = @Column(name = "CODIGO_RUBRO", nullable = false, length = 2)) })
	public ProyAnualId getId() {
		return this.id;
	}

	public void setId(ProyAnualId id) {
		this.id = id;
	}

	@Column(name = "REALIZADO", nullable = false, precision = 10)
	public BigDecimal getRealizado() {
		return this.realizado;
	}

	public void setRealizado(BigDecimal realizado) {
		this.realizado = realizado;
	}

	@Column(name = "META", nullable = false, precision = 10)
	public BigDecimal getMeta() {
		return this.meta;
	}

	public void setMeta(BigDecimal meta) {
		this.meta = meta;
	}

}
