package credCobGerClasses;

// Generated 06-24-2014 07:46:37 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * RubroProyeccion generated by hbm2java
 */
@Entity
@Table(name = "rubro_proyeccion", catalog = "CredCobGer")
public class RubroProyeccion implements java.io.Serializable {

	private String codigoRubro;
	private String nombre;

	public RubroProyeccion() {
	}

	public RubroProyeccion(String codigoRubro, String nombre) {
		this.codigoRubro = codigoRubro;
		this.nombre = nombre;
	}

	@Id
	@Column(name = "CODIGO_RUBRO", unique = true, nullable = false, length = 2)
	public String getCodigoRubro() {
		return this.codigoRubro;
	}

	public void setCodigoRubro(String codigoRubro) {
		this.codigoRubro = codigoRubro;
	}

	@Column(name = "NOMBRE", nullable = false, length = 20)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

}
