package credCobGerClasses;

// Generated 06-24-2014 07:46:37 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Sucursal generated by hbm2java
 */
@Entity
@Table(name = "sucursal", catalog = "CredCobGer")
public class Sucursal implements java.io.Serializable {

	private int numCorrSuc;
	private String nombreSuc;

	public Sucursal() {
	}

	public Sucursal(int numCorrSuc, String nombreSuc) {
		this.numCorrSuc = numCorrSuc;
		this.nombreSuc = nombreSuc;
	}

	@Id
	@Column(name = "NUM_CORR_SUC", unique = true, nullable = false)
	public int getNumCorrSuc() {
		return this.numCorrSuc;
	}

	public void setNumCorrSuc(int numCorrSuc) {
		this.numCorrSuc = numCorrSuc;
	}

	@Column(name = "NOMBRE_SUC", nullable = false, length = 20)
	public String getNombreSuc() {
		return this.nombreSuc;
	}

	public void setNombreSuc(String nombreSuc) {
		this.nombreSuc = nombreSuc;
	}

}
