package credCobGerClasses;

// Generated 06-24-2014 07:46:37 PM by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Telefono generated by hbm2java
 */
@Entity
@Table(name = "telefono", catalog = "CredCobGer")
public class Telefono implements java.io.Serializable {

	private TelefonoId id;
	private String numTel;

	public Telefono() {
	}

	public Telefono(TelefonoId id, String numTel) {
		this.id = id;
		this.numTel = numTel;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "codigoAs", column = @Column(name = "CODIGO_AS", nullable = false, length = 7)),
			@AttributeOverride(name = "numCor", column = @Column(name = "NUM_COR", nullable = false)) })
	public TelefonoId getId() {
		return this.id;
	}

	public void setId(TelefonoId id) {
		this.id = id;
	}

	@Column(name = "NUM_TEL", nullable = false, length = 8)
	public String getNumTel() {
		return this.numTel;
	}

	public void setNumTel(String numTel) {
		this.numTel = numTel;
	}

}
