package credCobGerClasses;

// Generated 06-24-2014 07:46:37 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TipoUsuario generated by hbm2java
 */
@Entity
@Table(name = "tipo_usuario", catalog = "CredCobGer")
public class TipoUsuario implements java.io.Serializable {

	private int codUsu;
	private String tipUsu;

	public TipoUsuario() {
	}

	public TipoUsuario(int codUsu, String tipUsu) {
		this.codUsu = codUsu;
		this.tipUsu = tipUsu;
	}

	@Id
	@Column(name = "COD_USU", unique = true, nullable = false)
	public int getCodUsu() {
		return this.codUsu;
	}

	public void setCodUsu(int codUsu) {
		this.codUsu = codUsu;
	}

	@Column(name = "TIP_USU", nullable = false, length = 10)
	public String getTipUsu() {
		return this.tipUsu;
	}

	public void setTipUsu(String tipUsu) {
		this.tipUsu = tipUsu;
	}

}
